spring.application.name=first-backend
port=8012

#spring.datasource.url=jdbc:postgresql://db:5432/mydb
#spring.datasource.username=postgres
#spring.datasource.password=password
spring.datasource.url=jdbc:postgresql://db:5432/mydb
spring.datasource.username=postgres
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
jwt.secret=e2a350504945d2eedb4a1bb98643fe33e99a0a8c848f91591d05bab7cd108685
jwt.expiration=10800000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=always
server.error.include-exception=true
